variables:
    GIT_SSL_NO_VERIFY: "true"
    GIT_SUBMODULE_STRATEGY: "recursive"
    DEVEL_HPP_DIR: "$CI_PROJECT_DIR/workspace"
    BUILD_TYPE: "Release"

.build_template: &build_definition
    stage: build
    script:
      - export INSTALL_DOCUMENTATION=OFF
      - cp -r /clean_workspace $DEVEL_HPP_DIR
      - $CI_PROJECT_DIR/script/auto-install-hpp.sh --branch ${CI_COMMIT_REF_NAME} --gitrepo https://gepgitlab.laas.fr/humanoid-path-planner/hpp-doc/raw --target benchmark
    artifacts:
      paths:
        - workspace

.test_template: &test_definition
    stage: test
    script:
      - echo -e "#!/bin/bash\nsource $DEVEL_HPP_DIR/config.sh\ncd $DEVEL_HPP_DIR/src/\$1/build-rel && make test" > $DEVEL_HPP_DIR/test.sh
      - cat $DEVEL_HPP_DIR/test.sh
      - chmod u+x $DEVEL_HPP_DIR/test.sh
      - $DEVEL_HPP_DIR/test.sh hpp-util
      - $DEVEL_HPP_DIR/test.sh hpp-fcl
      - $DEVEL_HPP_DIR/test.sh hpp-pinocchio
      - $DEVEL_HPP_DIR/test.sh hpp-statistics
      - $DEVEL_HPP_DIR/test.sh hpp-constraints
      - $DEVEL_HPP_DIR/test.sh hpp-core
        #- $DEVEL_HPP_DIR/test.sh hpp-corbaserver
      - $DEVEL_HPP_DIR/test.sh hpp-manipulation
      - $DEVEL_HPP_DIR/test.sh hpp-manipulation-urdf
        #- $DEVEL_HPP_DIR/test.sh hpp-manipulation-corba
      - $DEVEL_HPP_DIR/test.sh hpp-walkgen
      - $DEVEL_HPP_DIR/test.sh hpp-wholebody-step
        #- $DEVEL_HPP_DIR/test.sh hpp-wholebody-step-corba
    allow_failure: true
    artifacts:
      paths:
        - workspace

.doc_template: &doc_definition
    stage: deploy
    script:
      - export INSTALL_DOCUMENTATION=ON
      - make -C $DEVEL_HPP_DIR/src -s all
      - tar czf hpp.${CI_COMMIT_REF_NAME}.`date +"%Y%m%d"`.tar.gz $DEVEL_HPP_DIR/install/share/doc
    allow_failure: true
    artifacts:
      paths:
        - workspace

master-build:
    image: gepgitlab.laas.fr:4567/humanoid-path-planner/hpp-doc/master-premade:16.04
    only:
      - future
    <<: *build_definition

ubuntu-14.04-build:
    image: gepgitlab.laas.fr:4567/humanoid-path-planner/hpp-doc/ubuntu-14.04-premade:14.04
    only:
      - ubuntu-14.04
    <<: *build_definition

devel-build:
    image: gepgitlab.laas.fr:4567/humanoid-path-planner/hpp-doc/devel-premade:16.04
    only:
      -  devel
    <<: *build_definition

master-test:
    image: gepgitlab.laas.fr:4567/humanoid-path-planner/hpp-doc/master-premade:16.04
    dependencies:
      - master-build
    only:
      - future
    <<: *test_definition

ubuntu-14.04-test:
    image: gepgitlab.laas.fr:4567/humanoid-path-planner/hpp-doc/ubuntu-14.04-premade:14.04
    dependencies:
      - ubuntu-14.04-build
    only:
      - ubuntu-14.04
    <<: *test_definition

devel-test:
    image: gepgitlab.laas.fr:4567/humanoid-path-planner/hpp-doc/devel-premade:16.04
    dependencies:
      - devel-build
    only:
      -  devel
    <<: *test_definition

master-doc:
    image: gepgitlab.laas.fr:4567/humanoid-path-planner/hpp-doc/master-premade:16.04
    dependencies:
      - master-build
    only:
      - future
    <<: *doc_definition

ubuntu-14.04-doc:
    image: gepgitlab.laas.fr:4567/humanoid-path-planner/hpp-doc/ubuntu-14.04-premade:14.04
    dependencies:
      - ubuntu-14.04-build
    only:
      - ubuntu-14.04
    <<: *doc_definition

devel-doc:
    image: gepgitlab.laas.fr:4567/humanoid-path-planner/hpp-doc/devel-premade:16.04
    dependencies:
      - devel-build
    only:
      -  devel
    <<: *doc_definition
